"""
Generated by OAE
"""

from api.health import health


def main():
    info = health()

    print("=" * 40)
    print(info["service"])
    print("Status:", info["status"])
    print("=" * 40)


if __name__ == "__main__":
    main()
